[33mWARNING [0m urllib3.connectionpool:connectionpool.py:868 Retrying (Retry(total=2, connect=None, read=None, redirect=None, status=None)) after connection broken by 'NewConnectionError('<urllib3.connection.HTTPConnection object at 0x000001EA9DF27450>: Failed to establish a new connection: [WinError 10061] No connection could be made because the target machine actively refused it')': /session/5c99b2c81c5b01a45f543277a6daff10/element
[33mWARNING [0m urllib3.connectionpool:connectionpool.py:868 Retrying (Retry(total=1, connect=None, read=None, redirect=None, status=None)) after connection broken by 'NewConnectionError('<urllib3.connection.HTTPConnection object at 0x000001EA9DF26B50>: Failed to establish a new connection: [WinError 10061] No connection could be made because the target machine actively refused it')': /session/5c99b2c81c5b01a45f543277a6daff10/element
[33mWARNING [0m urllib3.connectionpool:connectionpool.py:868 Retrying (Retry(total=0, connect=None, read=None, redirect=None, status=None)) after connection broken by 'NewConnectionError('<urllib3.connection.HTTPConnection object at 0x000001EA9DF26850>: Failed to establish a new connection: [WinError 10061] No connection could be made because the target machine actively refused it')': /session/5c99b2c81c5b01a45f543277a6daff10/element