[33mWARNING [0m urllib3.connectionpool:connectionpool.py:868 Retrying (Retry(total=2, connect=None, read=None, redirect=None, status=None)) after connection broken by 'NewConnectionError('<urllib3.connection.HTTPConnection object at 0x00000236105D4510>: Failed to establish a new connection: [WinError 10061] No connection could be made because the target machine actively refused it')': /session/f3554345a3bc2dace76f4a53cd18f78f
[33mWARNING [0m urllib3.connectionpool:connectionpool.py:868 Retrying (Retry(total=1, connect=None, read=None, redirect=None, status=None)) after connection broken by 'NewConnectionError('<urllib3.connection.HTTPConnection object at 0x000002360E641850>: Failed to establish a new connection: [WinError 10061] No connection could be made because the target machine actively refused it')': /session/f3554345a3bc2dace76f4a53cd18f78f
[33mWARNING [0m urllib3.connectionpool:connectionpool.py:868 Retrying (Retry(total=0, connect=None, read=None, redirect=None, status=None)) after connection broken by 'NewConnectionError('<urllib3.connection.HTTPConnection object at 0x00000236105D55D0>: Failed to establish a new connection: [WinError 10061] No connection could be made because the target machine actively refused it')': /session/f3554345a3bc2dace76f4a53cd18f78f