{"name": "test_incorrect_username_correct_password_validation_error", "status": "passed", "attachments": [{"name": "stdout", "source": "f754286e-e36b-4c41-ad99-b3dd811135d9-attachment.txt", "type": "text/plain"}], "start": 1758037430738, "stop": 1758037433098, "uuid": "3c409917-d8a2-41a9-9f69-eb80ff984974", "historyId": "dc8509ded038b116f80c0bf384a36934", "testCaseId": "dc8509ded038b116f80c0bf384a36934", "fullName": "tests.test_login#test_incorrect_username_correct_password_validation_error", "labels": [{"name": "parentSuite", "value": "tests"}, {"name": "suite", "value": "test_login"}, {"name": "host", "value": "OTSI-Lap80"}, {"name": "thread", "value": "83536-MainThread"}, {"name": "framework", "value": "pytest"}, {"name": "language", "value": "cpython3"}, {"name": "package", "value": "tests.test_login"}]}