{"name": "test_correct_username_incorrect_password_validation_error", "status": "passed", "attachments": [{"name": "stdout", "source": "64386ac4-1ef6-4532-b9d4-3f342c4c848f-attachment.txt", "type": "text/plain"}], "start": 1757324560674, "stop": 1757324562994, "uuid": "52e9fede-804a-485a-9857-334886936772", "historyId": "e930212584cd195ca9e6b77f0c71884f", "testCaseId": "e930212584cd195ca9e6b77f0c71884f", "fullName": "tests.test_login#test_correct_username_incorrect_password_validation_error", "labels": [{"name": "parentSuite", "value": "tests"}, {"name": "suite", "value": "test_login"}, {"name": "host", "value": "OTSI-Lap80"}, {"name": "thread", "value": "88868-MainThread"}, {"name": "framework", "value": "pytest"}, {"name": "language", "value": "cpython3"}, {"name": "package", "value": "tests.test_login"}]}