{"name": "test_incorrect_username_correct_password_validation_error", "status": "passed", "attachments": [{"name": "stdout", "source": "4e2a2cb2-64a2-40bd-95ea-b2370462113d-attachment.txt", "type": "text/plain"}], "start": 1758040658995, "stop": 1758040661988, "uuid": "452bfd36-b3d9-4982-ac40-44b72f40e2c1", "historyId": "dc8509ded038b116f80c0bf384a36934", "testCaseId": "dc8509ded038b116f80c0bf384a36934", "fullName": "tests.test_login#test_incorrect_username_correct_password_validation_error", "labels": [{"name": "parentSuite", "value": "tests"}, {"name": "suite", "value": "test_login"}, {"name": "host", "value": "OTSI-Lap80"}, {"name": "thread", "value": "64864-MainThread"}, {"name": "framework", "value": "pytest"}, {"name": "language", "value": "cpython3"}, {"name": "package", "value": "tests.test_login"}]}