{"name": "test_correct_username_incorrect_password_validation_error", "status": "passed", "attachments": [{"name": "stdout", "source": "cb151fdc-63cf-49cd-9f53-84e9476fc01b-attachment.txt", "type": "text/plain"}], "start": 1757954966702, "stop": 1757954969771, "uuid": "e4a1578a-3729-4524-a97b-d5a91be126d0", "historyId": "e930212584cd195ca9e6b77f0c71884f", "testCaseId": "e930212584cd195ca9e6b77f0c71884f", "fullName": "tests.test_login#test_correct_username_incorrect_password_validation_error", "labels": [{"name": "parentSuite", "value": "tests"}, {"name": "suite", "value": "test_login"}, {"name": "host", "value": "OTSI-Lap80"}, {"name": "thread", "value": "82156-MainThread"}, {"name": "framework", "value": "pytest"}, {"name": "language", "value": "cpython3"}, {"name": "package", "value": "tests.test_login"}]}