{"name": "test_updated_password_login", "status": "failed", "statusDetails": {"message": "AssertionError: Login failed with updated password\nassert False", "trace": "driver = <selenium.webdriver.chrome.webdriver.WebDriver (session=\"f22c795f0e5474f7d3f51339520f1509\")>\n\n    @pytest.mark.usefixtures(\"driver\")\n    def test_updated_password_login(driver):\n        \"\"\"Test login with updated password.\"\"\"\n        driver.get(config[\"base_url\"])\n        username = config[\"forgotpassword\"][\"email\"]\n        password = config[\"forgotpassword\"][\"newpassword\"]\n        forgotpass = Forgotpassword(driver)\n        forgotpass.create_username(username)\n        forgotpass.create_password(password)\n        forgotpass.click_login_button()\n        time.sleep(4)\n        if forgotpass.is_logged_in():\n            print(\"User is able to login with updated password\")\n        else:\n>           assert False, \"Login failed with updated password\"\nE           AssertionError: Login failed with updated password\nE           assert False\n\ntests\\test_forgotpassword.py:331: AssertionError"}, "description": "Test login with updated password.", "attachments": [{"name": "stdout", "source": "8200ea56-6eaf-4d28-b965-ac323f4d97a5-attachment.txt", "type": "text/plain"}], "start": 1757781585681, "stop": 1757781601306, "uuid": "30497b20-a1b8-4d7d-b3a5-a6177e179877", "historyId": "c294af2d6f3ff16482e8fefdca6c2368", "testCaseId": "c294af2d6f3ff16482e8fefdca6c2368", "fullName": "tests.test_forgotpassword#test_updated_password_login", "labels": [{"name": "parentSuite", "value": "tests"}, {"name": "suite", "value": "test_forgotpassword"}, {"name": "host", "value": "OTSI-Lap80"}, {"name": "thread", "value": "54724-MainThread"}, {"name": "framework", "value": "pytest"}, {"name": "language", "value": "cpython3"}, {"name": "package", "value": "tests.test_forgotpassword"}]}