{"name": "test_correct_username_incorrect_password_validation_error", "status": "passed", "attachments": [{"name": "stdout", "source": "1a3ed00f-3187-476a-9df6-7c76cb2de71c-attachment.txt", "type": "text/plain"}], "start": 1758281042538, "stop": 1758281044844, "uuid": "011e7d01-29a6-46f7-95a9-c59b4e20e725", "historyId": "e930212584cd195ca9e6b77f0c71884f", "testCaseId": "e930212584cd195ca9e6b77f0c71884f", "fullName": "tests.test_login#test_correct_username_incorrect_password_validation_error", "labels": [{"name": "parentSuite", "value": "tests"}, {"name": "suite", "value": "test_login"}, {"name": "host", "value": "OTSI-Lap80"}, {"name": "thread", "value": "74352-MainThread"}, {"name": "framework", "value": "pytest"}, {"name": "language", "value": "cpython3"}, {"name": "package", "value": "tests.test_login"}]}