{"name": "test_incorrect_username_correct_password_validation_error", "status": "passed", "attachments": [{"name": "stdout", "source": "6970dc64-c724-47a1-b99c-07552f13b428-attachment.txt", "type": "text/plain"}], "start": 1758864777718, "stop": 1758864801473, "uuid": "60424a81-0c40-4fbe-88e8-18aaa26ce1d0", "historyId": "dc8509ded038b116f80c0bf384a36934", "testCaseId": "dc8509ded038b116f80c0bf384a36934", "fullName": "tests.test_login#test_incorrect_username_correct_password_validation_error", "labels": [{"name": "parentSuite", "value": "tests"}, {"name": "suite", "value": "test_login"}, {"name": "host", "value": "OTSI-Lap80"}, {"name": "thread", "value": "100080-MainThread"}, {"name": "framework", "value": "pytest"}, {"name": "language", "value": "cpython3"}, {"name": "package", "value": "tests.test_login"}]}