{"name": "test_login_correct_username_correct_password", "status": "failed", "statusDetails": {"message": "AssertionError: Login failed with correct username and correct password\nassert False", "trace": "driver = <selenium.webdriver.chrome.webdriver.WebDriver (session=\"78e04206030b5b80750a7d5eeea1e1b4\")>\n\n    @pytest.mark.usefixtures(\"driver\")\n    def test_login_correct_username_correct_password(driver):\n        \"\"\"Test login with correct username and correct password.\"\"\"\n        driver.get(config[\"base_url\"])\n        username = config[\"username\"]\n        password = config[\"password\"]\n        login_page = LoginPage(driver)\n        login_page.clear_field(login_page.username_input)\n        time.sleep(1)\n        login_page.create_username(username)\n        login_page.clear_field(login_page.password_input)\n        time.sleep(1)\n        login_page.create_password(password)\n        login_page.click_login_button()\n        time.sleep(4)\n        if login_page.is_logged_in():\n            print(\"Login test with correct username and correct password executed successfully!\")\n        else:\n>           assert False, \"Login failed with correct username and correct password\"\nE           AssertionError: Login failed with correct username and correct password\nE           assert False\n\ntests\\test_login.py:75: AssertionError"}, "description": "Test login with correct username and correct password.", "start": 1757309012686, "stop": 1757309024556, "uuid": "59a1eb74-4302-437e-9d45-2e6347afaa7c", "historyId": "73be65653c7801c1b3e9ad3c4844d02f", "testCaseId": "73be65653c7801c1b3e9ad3c4844d02f", "fullName": "tests.test_login#test_login_correct_username_correct_password", "labels": [{"name": "parentSuite", "value": "tests"}, {"name": "suite", "value": "test_login"}, {"name": "host", "value": "OTSI-Lap80"}, {"name": "thread", "value": "81632-MainThread"}, {"name": "framework", "value": "pytest"}, {"name": "language", "value": "cpython3"}, {"name": "package", "value": "tests.test_login"}]}