{"name": "test_correct_username_incorrect_password_validation_error", "status": "passed", "attachments": [{"name": "stdout", "source": "72484bd2-7292-41b7-aa6e-c467018bf6a2-attachment.txt", "type": "text/plain"}], "start": 1758040520542, "stop": 1758040523692, "uuid": "5850b638-2949-46f2-91ec-55cbf8bd4d26", "historyId": "e930212584cd195ca9e6b77f0c71884f", "testCaseId": "e930212584cd195ca9e6b77f0c71884f", "fullName": "tests.test_login#test_correct_username_incorrect_password_validation_error", "labels": [{"name": "parentSuite", "value": "tests"}, {"name": "suite", "value": "test_login"}, {"name": "host", "value": "OTSI-Lap80"}, {"name": "thread", "value": "62636-MainThread"}, {"name": "framework", "value": "pytest"}, {"name": "language", "value": "cpython3"}, {"name": "package", "value": "tests.test_login"}]}