{"name": "test_incorrect_username_correct_password_validation_error", "status": "passed", "attachments": [{"name": "stdout", "source": "1f59ac2e-491b-40b4-8aae-7ba84d2930f5-attachment.txt", "type": "text/plain"}], "start": 1757955252334, "stop": 1757955254965, "uuid": "1444b090-5f1f-4a5a-a7a4-0142316f5f81", "historyId": "dc8509ded038b116f80c0bf384a36934", "testCaseId": "dc8509ded038b116f80c0bf384a36934", "fullName": "tests.test_login#test_incorrect_username_correct_password_validation_error", "labels": [{"name": "parentSuite", "value": "tests"}, {"name": "suite", "value": "test_login"}, {"name": "host", "value": "OTSI-Lap80"}, {"name": "thread", "value": "82208-MainThread"}, {"name": "framework", "value": "pytest"}, {"name": "language", "value": "cpython3"}, {"name": "package", "value": "tests.test_login"}]}