{"name": "test_incorrect_username_correct_password_validation_error", "status": "passed", "attachments": [{"name": "stdout", "source": "f488b7a0-3b7b-4882-8694-df33a2f39cf4-attachment.txt", "type": "text/plain"}], "start": 1757955486731, "stop": 1757955489748, "uuid": "f4895181-d4fc-4fac-8a84-01afe526db4f", "historyId": "dc8509ded038b116f80c0bf384a36934", "testCaseId": "dc8509ded038b116f80c0bf384a36934", "fullName": "tests.test_login#test_incorrect_username_correct_password_validation_error", "labels": [{"name": "parentSuite", "value": "tests"}, {"name": "suite", "value": "test_login"}, {"name": "host", "value": "OTSI-Lap80"}, {"name": "thread", "value": "77216-MainThread"}, {"name": "framework", "value": "pytest"}, {"name": "language", "value": "cpython3"}, {"name": "package", "value": "tests.test_login"}]}