[33mWARNING [0m urllib3.connectionpool:connectionpool.py:868 Retrying (Retry(total=2, connect=None, read=None, redirect=None, status=None)) after connection broken by 'NewConnectionError('<urllib3.connection.HTTPConnection object at 0x000001DF7794F510>: Failed to establish a new connection: [WinError 10061] No connection could be made because the target machine actively refused it')': /session/e3e62a3ff1c3a53d9667897dd44a5489/element
[33mWARNING [0m urllib3.connectionpool:connectionpool.py:868 Retrying (Retry(total=1, connect=None, read=None, redirect=None, status=None)) after connection broken by 'NewConnectionError('<urllib3.connection.HTTPConnection object at 0x000001DF7794FE50>: Failed to establish a new connection: [WinError 10061] No connection could be made because the target machine actively refused it')': /session/e3e62a3ff1c3a53d9667897dd44a5489/element
[33mWARNING [0m urllib3.connectionpool:connectionpool.py:868 Retrying (Retry(total=0, connect=None, read=None, redirect=None, status=None)) after connection broken by 'NewConnectionError('<urllib3.connection.HTTPConnection object at 0x000001DF779311D0>: Failed to establish a new connection: [WinError 10061] No connection could be made because the target machine actively refused it')': /session/e3e62a3ff1c3a53d9667897dd44a5489/element
[33mWARNING [0m urllib3.connectionpool:connectionpool.py:868 Retrying (Retry(total=2, connect=None, read=None, redirect=None, status=None)) after connection broken by 'NewConnectionError('<urllib3.connection.HTTPConnection object at 0x000001DF778F7550>: Failed to establish a new connection: [WinError 10061] No connection could be made because the target machine actively refused it')': /session/e3e62a3ff1c3a53d9667897dd44a5489/element
[33mWARNING [0m urllib3.connectionpool:connectionpool.py:868 Retrying (Retry(total=1, connect=None, read=None, redirect=None, status=None)) after connection broken by 'NewConnectionError('<urllib3.connection.HTTPConnection object at 0x000001DF77931F50>: Failed to establish a new connection: [WinError 10061] No connection could be made because the target machine actively refused it')': /session/e3e62a3ff1c3a53d9667897dd44a5489/element
[33mWARNING [0m urllib3.connectionpool:connectionpool.py:868 Retrying (Retry(total=0, connect=None, read=None, redirect=None, status=None)) after connection broken by 'NewConnectionError('<urllib3.connection.HTTPConnection object at 0x000001DF7794D850>: Failed to establish a new connection: [WinError 10061] No connection could be made because the target machine actively refused it')': /session/e3e62a3ff1c3a53d9667897dd44a5489/element
[33mWARNING [0m urllib3.connectionpool:connectionpool.py:868 Retrying (Retry(total=2, connect=None, read=None, redirect=None, status=None)) after connection broken by 'NewConnectionError('<urllib3.connection.HTTPConnection object at 0x000001DF74405E90>: Failed to establish a new connection: [WinError 10061] No connection could be made because the target machine actively refused it')': /session/e3e62a3ff1c3a53d9667897dd44a5489
[33mWARNING [0m urllib3.connectionpool:connectionpool.py:868 Retrying (Retry(total=1, connect=None, read=None, redirect=None, status=None)) after connection broken by 'NewConnectionError('<urllib3.connection.HTTPConnection object at 0x000001DF779226D0>: Failed to establish a new connection: [WinError 10061] No connection could be made because the target machine actively refused it')': /session/e3e62a3ff1c3a53d9667897dd44a5489
[33mWARNING [0m urllib3.connectionpool:connectionpool.py:868 Retrying (Retry(total=0, connect=None, read=None, redirect=None, status=None)) after connection broken by 'NewConnectionError('<urllib3.connection.HTTPConnection object at 0x000001DF779B3D50>: Failed to establish a new connection: [WinError 10061] No connection could be made because the target machine actively refused it')': /session/e3e62a3ff1c3a53d9667897dd44a5489